[package]
name = "enemy_pathfinder"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = "0.4.14"
macroquad_tiled_clone = { git = "https://github.com/B3Z0/macroquad_tiled_clone" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
